feat: add support for computed values via skipped questions
copier-org/copier pull request #1220
Opened 2023-06-29 15:11 UTC by sisp

I've added support for a long awaited feature: computed values via skipped questions (`when: false`). :tada: See https://github.com/copier-org/copier/pull/1206#issuecomment-1605892551 for more details.

Supersedes #1206. Resolves #1204 #1205. Resolves (I guess ...) #1203. :stuck_out_tongue_winking_eye:

2023-06-29 15:31 UTC, yajo requested changes
Little improvement for docs. The rest looks great!

2023-06-29 15:31 UTC, yajo commented on docs/configuring.md
> +    If a question is skipped, no answer is recorded, but its default value is available
```suggestion
    If a question is skipped, its answer is not recorded, but its default value is available
```

2023-06-29 15:33 UTC, yajo commented
I'm thinking...  We're just adding a feature, but what if a template relied on the fact that a skipped question was always missing? Should we label this as a breaking change? 🤔

2023-06-29 15:43 UTC, sisp commented
Missing in the context? For this to be breaking, an injected variable through an extension like the context hooks one would need to have the same name as the skipped question. I guess, it can be breaking in rare cases. :thinking:

I forgot to edit the inline comments to describe the new behavior. I'll push a commit with corrected comments in a moment.

2023-06-29 15:49 UTC, yajo commented
Well, the feature was never supported, so after all any breakages would come from unsupported use. Thus we can consider this a normal improvement.

2023-06-29 15:55 UTC, sisp commented
I think this PR isn't quite right yet. We should make sure that a skipped question's answer can only ever be its default value but not a value passed via `--data` or read from an edited answers file. I'll look into it.

2023-06-29 16:03 UTC, yajo commented
> not a value passed via `--data` or read from an edited answers file

I think you don't need to care so deeply for this. Those are either weird or unsupported use cases anyways. If you do them, you know you're gonna get something wrong, so it should be OK for us IMHO.

2023-06-29 17:03 UTC, sisp commented
Alright, I guess we can keep it like it is now to ship it more quickly, possibly add more rigor later for those anyway weird cases.

2023-07-08 08:51 UTC, yajo commented
It seems you have style violations. Could you run pre-commit please?

2023-07-08 10:19 UTC, sisp commented
Ooops, yes, should be fixed now.

2023-07-08 10:36 UTC, merged

2023-07-08 10:48 UTC, pawamoy commented
Best PR :smiling_face_with_tear: Many users will be super happy about this!

2023-07-08 13:36 UTC, tlambert03 commented
thanks for your work on this @sisp!

I can confirm that with this PR, my template at https://github.com/pydev-guide/pyrepo-copier works as it did before v8

2023-07-08 13:42 UTC, sisp commented
More important is @yajo's careful assessment about the best implementation of this feature.