fix(vcs): prevent local clone from beiong stuck by gpg prompts
copier-org/copier pull request #1360
Opened 2023-10-05 17:19 UTC by noirbizarre

A quick and simple PR preventing the `copy` command to get stick if you have `commit.gpgSign` and try to run the `copy` command on WIP local project for trial.

2023-10-07 11:51 UTC, sisp reviewed
Thanks, @noirbizarre! :pray:

I think you're aiming for a subset of #856, which unfortunately seems abandoned. So, I anticipate updating a generated project with GPG commit signing enabled would be a problem for you, too. Would you be interest in finishing #856 here? I.e., add the `git config` line in `main.py` and adapt the tests accordingly? This would be in line with @yajo's pragmatic suggestion:

> Another option is forget about that and just add the `--no-gpg-sign` flag wherever needed. I don't think this would be too complicated honestly.
>
> &mdash; https://github.com/copier-org/copier/issues/1224#issuecomment-1646140385

Related to #1224.

2023-10-07 15:26 UTC, noirbizarre commented
Thanks, I didn saw it (my bad). I'll resubmit the PR integrating #1224 and #856 👍🏼

2023-10-08 05:45 UTC, yajo requested changes
There are still more git commits issued. Maybe it's the time to fix all?

https://github.com/copier-org/copier/blob/1196644aaf928d84201a893b0c769cef48c0cdeb/copier/main.py#L946-L947

https://github.com/copier-org/copier/blob/1196644aaf928d84201a893b0c769cef48c0cdeb/tests/helpers.py#L149

There are still more in the tests suite. See https://github.com/copier-org/copier/issues/616.

2023-10-08 16:58 UTC, noirbizarre commented
OK, there is in fact 2 distinct issues in this:
- tests runs with the user config which might conflict/interfere witht the test
- copier also commit with the user config but this is legit and should be properly handled

PR updated with the following:
- tests use a sandboxed `.gitconfig` using [`pytest-gitconfig`](https://pypi.org/project/pytest-gitconfig/)
- a test specific explicit test case has been added for the `user.gpgsigninkey`/`commit.gpgsign` to ensure copier is properly handling this case
- `--no-gpg-sign` has been added to copier commit calls only (it is faster and easier to maintain than trying to monkeypatch plumbum or gitconfigm there was only 3 calls)

If there are some new or untested case which might conflict with `user.gpgsigninkey`/`commit.gpgsign`, am explicit test case for this case should be added on the same model than `tests/test_dirty_local.py::test_copy_dirty_head_with_gpg`

2023-10-10 17:37 UTC, yajo approved these changes
Awesome!

2023-10-10 17:42 UTC, yajo commented
I made a push including https://github.com/nix-community/poetry2nix/pull/1342 to see if that fixes the build.

2023-10-11 11:09 UTC, noirbizarre commented
I have no expertise on Nix and I really can't help on this part.

TBH I was surprise with the `.envrc` automatically building for 30min and I wonder if this part should be optin and excluded from CI ? It feels like artificially raising the complexity with an hard system dependency. NiX is meant for reproducibility but I can't reproduce this error, build pass as well as pre-commit checks 🤷‍♂️

However I am the `pytest-gitconfig` author so if something is needed for NiX compatibility (given the module it would be surprizing, but again, I am not knowledgeable on NiX), tell me, I'll do the change (this is the first time I encounter an error on this one)

2023-10-11 12:28 UTC, yajo commented
Don't worry, it's just a common routine for projects like this one that use poetry2nix. There's nothing special for you to do in pytest-gitconfig to add that compatibility.

Using nix is just because it's great! Most concerns about it is "it's complex", but in reality, once you learn it, it removes lots of complexities. It's obsoleting containers. I just can't live without it. 🤷🏼‍♂️ 

Regarding test failures, I see mypy failures (probably typing errors in some test) and also gpg signinig failures. It seems like, when you wanted to skip gpg, you actually enabled it everywhere! But you can see that all versions of CI (even those that don't use Nix) are broken, so it doesn't seem like a Nix problem at first sight.

I wouldn't like to go too off-topic about nix here, but if you have any questions please feel free to open thread(s) in the forum. 😊

2023-10-15 22:08 UTC, noirbizarre commented
Last failures were due to:
- a `pytest-gitconfig` compatibility issue with 3.8
- `plumbum.local.env` being snapshotted once at start and requiring its own monkeypatching has changes to `os.environ` are ignored

PR (and `pytest-gitconfig`) updated and should be fixed 👍🏼

2023-10-16 12:51 UTC, sisp requested changes

2023-10-16 12:51 UTC, sisp commented on pyproject.toml
IIRC from own experience, these formatting changes are caused by a VS Code TOML extension. Would you mind undoing them and saving the file without formatting, @noirbizarre?

2023-10-16 16:45 UTC, noirbizarre commented on pyproject.toml
Done 👍🏼 

However, I can't explain windows errors:
- doesn't seem directly related to this change
- fails only on windows (which I can't reproduce, I only have Linux)
But I'll try to find out why.

Is it possible to remove the approval for the workflow (if you can do it on user or PR based)? 
Because this is rather hard to push and wait days to see if CI is green or still needs a fix while I could have probably fixed it in the same time (The windows part, I can't have seen it before has windows and Mac tests are passing). 
(I am curious, this is not the only open source project with a workflow approval to run on PRs, what is justifying that ?)

2023-10-17 08:24 UTC, noirbizarre commented
Sorry, comment posted in the wrong place.

Note: @yajo for nix it was just bad timing, latest update was broken for 3 days on `archlinux`. It's now fixed and it works 👍🏼 

EDIT: I think I also found the Windows issue: some git parameter were set from outside in CI (and so ignored by `pytest-gitconfig` doing it's job). Given `user.name` and `user.email` are already automatically set by `pytest-gitconfig`, I think windows was just missing the `core.autocrlf=input`. Ci should pass (unless there are other Windows specific issues)

2023-10-22 13:06 UTC, yajo approved these changes

2023-10-22 13:20 UTC, merged