docs: improve updating pre-commit documentation
copier-org/copier pull request #1361
Opened 2023-10-06 11:55 UTC by 12rambau

- there was a inconsistence between the inline and rej default. as it's inline I changed the value in the corrected section
- as users won't need the 2 options at once, I split the 2 hooks.

2023-10-06 14:07 UTC, sisp requested changes
Thanks for your contribution and also for catching the outdated default value for the `--conflict` flag, @12rambau! :pray:

I have only a few minor remarks.

2023-10-06 14:07 UTC, sisp commented on docs/updating.md
> +If you use `--conflict inline` (the default) then you need to check for conflicts marks in your files:
* `marks` ->  `markers`
* An empty line is missing.
* The line length exceeds 88 characters, so [Prettier won't be happy](https://github.com/copier-org/copier/blob/5fa3b9fb772101ac67476ab235b8e66ca26900de/.prettierrc.yml#L1).

```suggestion
If you use `--conflict inline` (the default) then you need to check for conflicts
markers in your files:

```

2023-10-06 14:07 UTC, sisp commented on docs/updating.md
> +If you use `--conflict rej` Then you need to reject all the generated `.rej` files:
Some spelling, wording and content improvements:

```suggestion
If you use `--conflict rej` then you need to review and remove all generated `.rej`
files:
```

2023-10-08 05:50 UTC, yajo requested changes
I think it's good to keep both examples together. In a shared project, one user might use  rej mode, while others use inline mode. In any case, you don't want those files committed.

If you want to keep them split because of clarity, at least please explain this point too.

2024-01-12 10:56 UTC, bswck commented
The current documentation is confusing. At first it is stated that `--conflict inline` is the default, and later that `--conflict rej` is.

2024-01-15 07:42 UTC, yajo commented
In that case, the default is inline.

2024-01-15 17:50 UTC, yajo approved these changes

2024-01-15 18:12 UTC, sisp requested changes
Just some final polishing. :wink:

2024-01-15 18:12 UTC, sisp commented on docs/updating.md
> +            entry: found Copier update rejection files; review and remove them before merging.
This was actually incorrect before: [`entry`](https://pre-commit.com/#hooks-entry) refers to the executable to run. This is a [description](https://pre-commit.com/#hooks-description):

```suggestion
            description: found Copier update rejection files; review and remove them before merging.
```

2024-01-15 18:12 UTC, sisp commented on docs/updating.md
> +    of these files are committed.
Just some minor suggestions for better clarity and grammatical correctness:

```suggestion
    For projects that use both `rej` and `inline` depending on each user's preference,
    you can add both hooks to your `pre-commit-config.yaml` file, making sure that no
    unresolved merge conflicts are committed.
```

2024-01-15 18:19 UTC, sisp commented
Oh, and CI is failing because Prettier wants a line wrap in the `pre-commit-config.yaml` snippet. It's probably best to make this a proper multiline YAML string:

```yaml
description: >
  found Copier ...
  ...
```

2024-01-15 18:25 UTC, yajo commented
Fixed

2024-01-15 18:32 UTC, sisp approved these changes
Perfect, thanks! :ok_hand:

2024-01-15 18:43 UTC, merged