gitignored file
copier-org/copier pull request #1373
Opened 2023-10-16 16:35 UTC by hparfr

a file in the template but gitignored in the project should persist in the filesystem

fixes #1162

2023-10-22 13:13 UTC, yajo requested changes

2023-10-22 13:13 UTC, yajo commented on copier/main.py
> +                extra_exclude = [filename.split('!! ').pop() for filename in ignored_files.split("\n")][:-1]
Same thing, more readable:

```suggestion
                extra_exclude = [filename.split('!! ').pop() for filename in ignored_files.splitlines()]
```

2023-10-22 13:13 UTC, yajo commented on tests/test_updatediff.py
> +        Path(".git/info/exclude").write_text("toignore.txt")
Users don't usually do this. It's more common:

```suggestion
        Path(".gitignore").write_text("toignore.txt")
        git("commit", "-Am" "ignore file")
```

You can test both scenarios too by ignoring 2 files using those 2 different methods.

2023-10-22 13:14 UTC, yajo commented
Looks like you have to reformat the code. Run `poe lint` to do it automatically please.

2023-10-23 08:28 UTC, hparfr commented on copier/main.py
> +                extra_exclude = [filename.split('!! ').pop() for filename in ignored_files.split("\n")][:-1]
Good to know :+1:

2023-10-23 08:31 UTC, hparfr commented
Thanks @yajo  for your review

2023-10-23 19:10 UTC, yajo approved these changes
Thanks!

2023-10-24 14:24 UTC, yajo requested changes

2023-10-24 15:20 UTC, hparfr commented
I hope this one is the good one :)

2023-10-28 02:55 UTC, yajo approved these changes

2023-11-07 14:06 UTC, hparfr commented
There war an issue with flake-check, I rebased and squashed on master

2023-11-15 13:05 UTC, sisp approved these changes
Excellent work! :ok_hand: Thanks! :pray:

2023-11-15 13:06 UTC, merged