fix(actions): swap sha256sum for shasum -a 256
copier-org/copier pull request #1390
Opened 2023-10-29 11:01 UTC by kenibrewer

This addresses an issue in macOS builds may be impacting caching. The command `sha256sum` which doesn't exist in `macOS-latest` is replaced with `shasum -a 256` which is present in both `ubuntu-latest` and `macOS-latest`

Closes #1389

2023-10-29 11:42 UTC, sisp requested changes
Thanks for discovering this error and taking the initiative to fix it, @kenibrewer! :pray:

Your current fix works for macOS and Ubuntu, but it doesn't work for Windows:

```
D:\a\_temp\29fa6760-37f4-4d7b-9324-e184f44d2852.sh: line 1: shasum: command not found
```

I see three options:

1. Use Python's `hashlib` module (see my inline suggestions).
1. Use the [cache key computation from Poetry's own CI config](https://github.com/python-poetry/poetry/blob/e12ca037bf0ff5faa93179270ef7c012f8e9ecdd/.github/workflows/main.yml#L76-L90).
1. Make this step conditioned on the OS and add another one with `sha256sum` for Windows.

2023-10-29 11:42 UTC, sisp commented on .github/workflows/ci.yml
> +          echo "PY=$((python -VV; pip freeze) | shasum -a 256 | cut -d' ' -f1)" >>
```suggestion
          echo "PY=$((python -VV; pip freeze) | python -uc 'import hashlib, sys; print(hashlib.sha256(sys.stdin.buffer.read()).hexdigest())' | cut -d' ' -f1)" >>
```

2023-10-29 11:42 UTC, sisp commented on .github/workflows/ci.yml
> +          echo "PY=$((python -VV; pip freeze) | shasum -a 256 | cut -d' ' -f1)" >>
```suggestion
          echo "PY=$((python -VV; pip freeze) | python -uc 'import hashlib, sys; print(hashlib.sha256(sys.stdin.buffer.read()).hexdigest())' | cut -d' ' -f1)" >>
```

2023-10-29 13:32 UTC, kenibrewer commented
> 1. Use Python's `hashlib` module (see my inline suggestions).
> 2. Use the [cache key computation from Poetry's own CI config](https://github.com/python-poetry/poetry/blob/e12ca037bf0ff5faa93179270ef7c012f8e9ecdd/.github/workflows/main.yml#L76-L90).
> 3. Make this step conditioned on the OS and add another one with `sha256sum` for Windows.
> 
> I'm leaning towards solution 2, but solution 1 is less intrusive. Solution 3 adds too much duplicate code for my taste, but I wanted to mention it nevertheless.

I like solution 2 best as well. It's a lot more readable while solution 1 is pretty hard to parse.

2023-10-29 14:16 UTC, kenibrewer commented
@sisp Can I get another workflow run?

2023-10-29 14:30 UTC, kenibrewer commented
Looks like that didn't work for the windows install either. 

```
Run echo version=$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info))") >> $GITHUB_OUTPUT
  echo version=$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info))") >> $GITHUB_OUTPUT
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
  env:
    LANG: en_US.utf-8
    LC_ALL: en_US.utf-8
    PIP_CACHE_DIR: D:\a\copier\copier/.cache/pip
    POETRY_CACHE_DIR: D:\a\copier\copier/.cache/pypoetry
    POETRY_VIRTUALENVS_IN_PROJECT: true
    PRE_COMMIT_HOME: D:\a\copier\copier/.cache/pre-commit
    PYTEST_ADDOPTS: 
    PYTHONIOENCODING: UTF-8
    pythonLocation: C:\hostedtoolcache\windows\Python\3.9.13\x64
    PKG_CONFIG_PATH: C:\hostedtoolcache\windows\Python\3.9.13\x64/lib/pkgconfig
    Python_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.9.13\x64
    Python[2](https://github.com/copier-org/copier/actions/runs/6683900995/job/18160692065?pr=1390#step:5:2)_ROOT_DIR: C:\hostedtoolcache\windows\Python\[3](https://github.com/copier-org/copier/actions/runs/6683900995/job/18160692065?pr=1390#step:5:3).9.13\x6[4](https://github.com/copier-org/copier/actions/runs/6683900995/job/18160692065?pr=1390#step:5:4)
    Python3_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.9.13\x64

Cache restored successfully
Cache restored from key: cache|Windows||212c846ea7c96894e2ee344b3ed706190f898f3da49de7092b13c63149eea81b|c860f4[5]
```

I set up a test PR into my own fork so I can run the workflows myself. I'll probably test option 1 next and see if I can make it clearer and readable.

2023-11-03 19:57 UTC, kenibrewer commented
@sisp This is now passing all tests and generates cache keys on all platforms.

2023-11-04 07:43 UTC, yajo approved these changes

2023-11-04 11:04 UTC, sisp approved these changes
Perfect, @kenibrewer, thank you! :pray:

2023-11-04 11:04 UTC, merged