Document behavior of generating destination path when copying
copier-org/copier pull request #1498
Opened 2024-02-05 12:06 UTC by phinate

Documents #1497.

2024-02-05 12:53 UTC, pawamoy reviewed
A few suggestions in case other maintainers wish to accept this change.

2024-02-05 12:53 UTC, pawamoy commented on README.md
> +If `path/to/destination` doesn't exist, `copier` will create the directory in both cases.
```suggestion
If `path/to/destination` doesn't exist, Copier will create the directory.
```

2024-02-05 12:53 UTC, pawamoy commented on docs/generating.md
> +If `path/to/destination` doesn't exist, `copier` will both create and populate the directory with the generated files. Note that this will raise an error if the destination is read-only.
```suggestion
If `path/to/destination` doesn't exist, Copier will create the directory and populate it with the generated files. If `path/to/destination` exists, it must be writable (not read-only).
```

2024-02-20 06:10 UTC, yajo commented
There are formatting issues. Please run `poetry run poe lint` and push the new changes.

2024-02-25 12:26 UTC, sisp requested changes

2024-02-25 12:26 UTC, sisp commented on README.md
> +        ```
I don't think these indentation changes are necessary.

2024-03-09 08:31 UTC, yajo requested changes

2024-03-09 08:31 UTC, yajo commented on README.md
> +    If `path/to/destination` doesn't exist, Copier will create the directory.
I think you can just leave it documented in ˋgenerating.mdˋ. This way, the README is shorter. It's not something with so much importance so as to live in the README IMHO.

2025-02-22 12:45 UTC, pawamoy reviewed
Wrapping this up.

2025-02-22 12:45 UTC, pawamoy commented on README.md
> +        from copier import run_copy
```suggestion
    ```python
    from copier import run_copy
```

2025-02-22 12:45 UTC, pawamoy commented on README.md
> +        run_copy("path/to/project/template", "path/to/destination")
```suggestion
    # Create a project from a local path
    run_copy("path/to/project/template", "path/to/destination")
```

2025-02-22 12:45 UTC, pawamoy commented on README.md
> +        run_copy("https://github.com/copier-org/copier.git", "path/to/destination")
```suggestion
    # Or from a Git URL.
    run_copy("https://github.com/copier-org/copier.git", "path/to/destination")
```

2025-02-22 12:45 UTC, pawamoy commented on README.md
> +        run_copy("gh:copier-org/copier.git", "path/to/destination")
```suggestion
    # You can also use "gh:" as a shortcut of "https://github.com/"
    run_copy("gh:copier-org/copier.git", "path/to/destination")
```

2025-02-22 12:45 UTC, pawamoy commented on README.md
> +        run_copy("gl:copier-org/copier.git", "path/to/destination")
```suggestion
    # Or "gl:" as a shortcut of "https://gitlab.com/"
    run_copy("gl:copier-org/copier.git", "path/to/destination")
```

2025-02-22 12:45 UTC, pawamoy commented on README.md
> +    If `path/to/destination` doesn't exist, Copier will create the directory.
```suggestion
```

2025-02-22 12:46 UTC, pawamoy commented on README.md
> +        ```
```suggestion
    ```
```

2025-02-22 12:46 UTC, pawamoy approved these changes
Applied suggestions.

2025-02-22 17:39 UTC, pawamoy commented
RTD failure seems unrelated, if another maintainer can force-merge, I'd appreciate.

2025-02-28 20:31 UTC, sisp approved these changes

2025-03-05 20:09 UTC, pawamoy commented
@yajo could you merge / approve? :pray:

2025-03-09 20:02 UTC, merged