add 'pygrep' lint group
copier-org/copier pull request #1505
Opened 2024-02-06 20:10 UTC by danieleades

2024-02-06 20:17 UTC, danieleades commented
some of the formatting changes here surprise me. probably used to using a different version of ruff? i don't see anywhere where the version of ruff is pinned. Am i missing something?

2024-02-11 12:47 UTC, sisp requested changes
There's a minor Ruff linting error:

```
devtasks.py:63:9: PGH002 `warn` is deprecated in favor of `warning`
```

2024-02-11 13:01 UTC, danieleades commented
> There's a minor Ruff linting error:
> 
> ```
> devtasks.py:63:9: PGH002 `warn` is deprecated in favor of `warning`
> ```

should be resolved now.

Oddly, i couldn't reproduce this error locally using `poetry run ruff check .`

2024-02-11 13:35 UTC, sisp approved these changes
LGTM! :tada: Thanks, @danieleades! :pray:

2024-02-11 13:37 UTC, merged