Do not overwrite identical files
copier-org/copier pull request #1576
Opened 2024-04-07 01:54 UTC by kefirbandi

If _render_allowed identifies identical source and target, then only returns True if the path refers to a directory, not a file.

2024-04-07 05:52 UTC, sisp commented
Just a test is missing (see https://github.com/copier-org/copier/discussions/1092#discussioncomment-9027925).

Resolves #1092.

2024-04-07 15:11 UTC, yajo commented
Cool! Do you know how to add the test then?

2024-04-08 02:16 UTC, kefirbandi commented
> Cool! Do you know how to add the test then?

I would use the testcase: [test_skip_if_exists](https://github.com/copier-org/copier/blob/master/tests/test_copy.py#L285) as an example, and write something along the lines of:
```
def test_timestamp_identical(tmp_path: Path) -> None:
    copier.run_copy(str(Path("tests", "demo_skip_dst")), tmp_path)
    modification_time_before = ...
    sleep(2)
    copier.run_copy(str(Path("tests", "demo_skip_dst")), tmp_path)
    modification_time_after = ...

    assert modification_time_before == modification_time_after
   
```
Does it make sense?

2024-04-08 13:54 UTC, yajo commented
Ok

El lun, 8 abr 2024, 3:17, Andras Gefferth ***@***.***>
escribió:

> Cool! Do you know how to add the test then?
>
> I would use the testcase: test_skip_if_exists
> <https://github.com/copier-org/copier/blob/master/tests/test_copy.py#L285>
> as an example, and write something along the lines of:
>
> def test_timestamp_identical(tmp_path: Path) -> None:
>     copier.run_copy(str(Path("tests", "demo_skip_dst")), tmp_path)
>     modification_time_before = ...
>     sleep(2)
>     copier.run_copy(str(Path("tests", "demo_skip_dst")), tmp_path)
>     modification_time_after = ...
>
>     assert modification_time_before == modification_time_after
>
>
> Does it make sense?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/copier-org/copier/pull/1576#issuecomment-2041745619>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAHNXDLIVFV47LTXYJAHL3TY4H42NAVCNFSM6AAAAABF24WGXCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDANBRG42DKNRRHE>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-04-18 13:34 UTC, sisp requested changes
Just a minor linter error. LGTM otherwise! :tada:

2024-04-18 13:34 UTC, sisp commented on tests/test_copy.py
>  import filecmp
Ruff is unhappy because of the import order:

```suggestion
import filecmp
import os
```

2024-04-20 04:41 UTC, yajo approved these changes

2024-04-20 08:48 UTC, sisp requested changes

2024-04-20 08:48 UTC, sisp commented on tests/test_copy.py
> +
There are still minor linter errors:

```
> editorconfig-checker.....................................................Failed
> - hook id: editorconfig-checker
> - exit code: 1
>
> tests/test_copy.py:
>    310: Trailing whitespace
>       311: Trailing whitespace
> 
> 2 errors found
```

2024-04-21 09:53 UTC, sisp approved these changes

2024-04-21 09:54 UTC, merged