Supply official shields.io badges
copier-org/copier pull request #1615
Opened 2024-04-29 15:16 UTC by itz-salemm

Fix #1575

Please kindly note that the URL used in the README file is the copier-org which does not have the JSON badge file yet. Once the files are merged into the master. It should work fine

2024-04-29 16:01 UTC, yajo requested changes
I think you should add some docs, so people can use this.

2024-04-29 16:01 UTC, yajo commented on =
Please remove this file.

2024-04-30 09:53 UTC, itz-salemm commented
The badge docs has been added to the repo.

2024-05-01 10:56 UTC, sisp reviewed
I love badges and it's fantastic that Copier is getting one. But I wonder whether it's a bit too much to dedicate an entire documentation page to it. How about following a similar approach as https://github.com/astral-sh/ruff/blob/main/README.md#show-your-support and give it a section "Show your support" in our README file? The README file is also used as the landing page of our docs. Like Ruff, we could include examples for Markdown, reStructuredText, and plain HTML. In addition, we'd show our badge variations. But we'd keep it short and concise.

WDYT?

2024-05-01 10:56 UTC, sisp commented on =
This one: https://github.com/itz-salemm/copier/blob/supply-official-shields.io-badges/%3D

2024-05-01 11:27 UTC, itz-salemm commented
Done

2024-05-01 11:39 UTC, sisp requested changes

2024-05-01 11:39 UTC, sisp commented on README.md
> +```
I think we should disable Prettier here and keep the HTML markup in one long line:


````suggestion
<!-- prettier-ignore-start -->
```html
<a href="https://github.com/copier-org/copier"><img src="https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/copier-org/copier/master/img/badge/badge-grayscale-inverted-border-orange.json" alt="Copier" style="max-width:100%;"/></a>
```
<!-- prettier-ignore-end -->
````

I also removed a `(` at the beginning of the `src` URL that didn't belong there.

2024-05-01 11:39 UTC, sisp commented on README.md
> +7. Badge Grayscale Inverted Border Purple
Please use always `1.` for enumeration:


```suggestion
1. Badge Grayscale Border
   [![Copier](https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/copier-org/copier/master/img/badge/badge-grayscale-border.json)](https://github.com/copier-org/copier)

1. Badge Grayscale Inverted Border Orange
   [![Copier](https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/copier-org/copier/master/img/badge/badge-grayscale-inverted-border-orange.json)](https://github.com/copier-org/copier)

1. Badge Grayscale Inverted Border Red
   [![Copier](https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/copier-org/copier/master/img/badge/badge-grayscale-inverted-border-red.json)](https://github.com/copier-org/copier)

1. Badge Grayscale Inverted Border Teal
   [![Copier](https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/copier-org/copier/master/img/badge/badge-grayscale-inverted-border-teal.json)](https://github.com/copier-org/copier)

1. Badge Grayscale Inverted Border
   [![Copier](https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/copier-org/copier/master/img/badge/badge-grayscale-inverted-border.json)](https://github.com/copier-org/copier)

1. Black Badge
   [![Copier](https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/copier-org/copier/master/img/badge/black-badge.json)](https://github.com/copier-org/copier)

1. Badge Grayscale Inverted Border Purple
```

2024-05-01 11:46 UTC, itz-salemm commented
Thanks for the changes. Done

2024-05-01 12:33 UTC, sisp commented on img/badge/black-badge.json
Just one last request: I think it would be more consistent to rename this file (and its references in the badge URLs) to `badge-black.json`.

2024-05-01 12:41 UTC, itz-salemm commented on img/badge/black-badge.json
Yeah, sure.

Sorry about that.

2024-05-01 12:46 UTC, itz-salemm commented on img/badge/black-badge.json
Yeah, sure.

Sorry about that.

2024-05-01 14:16 UTC, sisp requested changes

2024-05-01 14:16 UTC, sisp commented on README.md
> +   [![Copier](https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/copier-org/copier/master/img/badge/badge-grayscale-inverted-border-purple.json)](https://github.com/copier-org/copi
Sprry, I just stumbler over one more tiny detail regarding the order of the badges:


```suggestion
1. Badge Grayscale Border
   [![Copier](https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/copier-org/copier/master/img/badge/badge-grayscale-border.json)](https://github.com/copier-org/copier)

1. Badge Grayscale Inverted Border
   [![Copier](https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/copier-org/copier/master/img/badge/badge-grayscale-inverted-border.json)](https://github.com/copier-org/copier)

1. Badge Grayscale Inverted Border Orange
   [![Copier](https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/copier-org/copier/master/img/badge/badge-grayscale-inverted-border-orange.json)](https://github.com/copier-org/copier)

1. Badge Grayscale Inverted Border Red
   [![Copier](https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/copier-org/copier/master/img/badge/badge-grayscale-inverted-border-red.json)](https://github.com/copier-org/copier)

1. Badge Grayscale Inverted Border Teal
   [![Copier](https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/copier-org/copier/master/img/badge/badge-grayscale-inverted-border-teal.json)](https://github.com/copier-org/copier)

1. Badge Grayscale Inverted Border Purple
   [![Copier](https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/copier-org/copier/master/img/badge/badge-grayscale-inverted-border-purple.json)](https://github.com/copier-org/copier)

1. Badge Black
   [![Copier](https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/copier-org/copier/master/img/badge/badge-black.json)](https://github.com/copier-org/copier)
```

This order seems more systematic.

2024-05-01 15:03 UTC, sisp approved these changes
Perfect, thank you very much! :pray:

2024-05-01 15:06 UTC, itz-salemm commented
Thank you for taking your time.

2024-05-07 21:42 UTC, yajo approved these changes

2024-05-07 21:43 UTC, merged