fix: Missing passing of `skip_tasks` flag
copier-org/copier pull request #1688
Opened 2024-07-02 15:00 UTC by arnaubt

Coulnd't get the `--skip-flags` option working until I passed the option to the worker.

2024-07-02 16:50 UTC, sisp requested changes
Thanks for discovering and fixing this bug, @arnaubt! :pray: LGTM! :tada:

Just one request. It would be great to have a test, e.g. similar to:

https://github.com/copier-org/copier/blob/3f89b71cc6116e2f6dcda3ceb3ce4a41301895b8/tests/test_unsafe.py#L94-L113

Would you mind adding one?

2024-07-03 08:52 UTC, arnaubt commented
@sisp Sure enough, test added! Let me know if it's good enough.

2024-07-03 09:05 UTC, sisp requested changes
LGTM, just some minor requests. Sorry that I was a bit imprecise, I was thinking to add the test in `tests/test_tasks.py` perhaps below

https://github.com/copier-org/copier/blob/3f89b71cc6116e2f6dcda3ceb3ce4a41301895b8/tests/test_tasks.py#L69-L82

Could you please move it there?

2024-07-03 09:05 UTC, sisp commented on tests/test_unsafe.py
> +        assert (dst / "task.txt").exists()
I think we can simplify this a bit like this:

```suggestion
    assert (dst / "task.txt").exists() is (not skip_tasks)
```

WDYT?

2024-07-03 09:05 UTC, sisp commented on tests/test_unsafe.py
> +
Just a minor cosmetic thing: No need for empty lines here.

```suggestion
    assert retcode == 0
```

2024-07-03 09:49 UTC, arnaubt commented
Test moved and suggestions applied, thanks!

2024-07-03 13:17 UTC, sisp commented on tests/test_tasks.py
> +
I forgot to remove the other empty line. Let me just remove it quickly myself.

```suggestion
```

2024-07-03 13:17 UTC, sisp approved these changes
LGTM! :tada: Thanks again, @arnaubt! :pray:

2024-07-03 13:27 UTC, merged

2024-07-03 13:44 UTC, sisp commented
@yajo is creating releases for us. Would you be open to and available for making a quick patch release, @yajo?

2024-07-03 16:09 UTC, yajo commented
Released!
https://github.com/copier-org/copier/releases/tag/v9.3.1

2024-07-03 16:49 UTC, sisp commented
Thank you very much! :pray: