Document how to update when changing a multiselect base answer
copier-org/copier pull request #1781
Opened 2024-09-20 15:40 UTC by kenden

Document how to update when changing a multiselect base answer
The documentation to update, changing only one answer  when the question is a multi-select base choice, is missing.

This is from https://github.com/copier-org/copier/issues/1474#issuecomment-2328522026, but it also indicates to create the `.yaml` file in another directory (to avoid error `Destination repository is dirty; cannot continue. Please commit or stash your local changes and retry.`).

2024-09-21 05:00 UTC, yajo requested changes
Thank you! I'd be happier to merge the fix rather than documenting the workaround, but at least it's something.

would you please mention the issue and tell something that indicates the reader that this is just a workaround until it's fixed?

2024-09-21 19:39 UTC, kenden commented on docs/updating.md
> +then you first need to create a file outside of the directory, e.g. `~/tmp/copier_answer.yaml`, with the content you want, e.g.:
Thanks! I made a change to use this instead.

2024-09-22 07:03 UTC, yajo requested changes

2024-09-22 07:03 UTC, yajo commented on docs/updating.md
> +As a workaround, you need to use the `--data_file` option instead. See [here](https://copier.readthedocs.io/en/stable/configuring/#data_file) for usage information.
```suggestion
As a workaround, for now you need to use [the `--data-file` option][data_file] instead.
```

2024-09-22 07:03 UTC, yajo commented on docs/updating.md
> +Note: it is not yet possible ([ref. issue](https://github.com/copier-org/copier/issues/1474)) to update a multiselect base choice that way, for example a value that
```suggestion
Note: it is not yet possible ([ref. issue](https://github.com/copier-org/copier/issues/1474)) to update a multiselect choice that way, for example a value that
```

2024-09-22 07:21 UTC, yajo approved these changes
I pushed by myself some changes to adapt to the global copywriting style, to avoid bothering you with the details. But the essence is the same. Also, after all, the ˋ--data-fileˋ option should be documented here, no matter if it is as a workaround or not.

Thank you!

2024-09-22 07:33 UTC, merged