Update docs dependencies versions
copier-org/copier pull request #266
Opened 2020-09-04 10:21 UTC by pawamoy

- `pymdown-extensions` v8 support was added in `mkdocstrings` v0.13.0
- `mkdocstrings` v0.13.1 fixes cross-references links (they are now relative to each other)

Therefore we were able to clean up the Poetry dependencies a bit :slightly_smiling_face:

2020-09-04 10:23 UTC, pawamoy commented
Oh, I'm using Poetry 1.1, it seems lock file are not compatible. I'll fix this on my end.

2020-09-04 10:31 UTC, pawamoy commented
Cross-references seem to be working fine!

2020-09-04 12:47 UTC, Yajo requested changes
Please fix too https://github.com/copier-org/copier/blob/d949d51ad3c679cad3d3b3dce4e85a8b8925a2f8/mkdocs.yml#L3-L5

2020-09-04 12:58 UTC, pawamoy commented
Done

2020-09-05 09:22 UTC, Yajo approved these changes

2020-09-05 09:22 UTC, merged

2020-09-05 09:22 UTC, Yajo commented
Thanks! :rocket: