Fix temporary directory removal on Windows
copier-org/copier pull request #358
Opened 2021-02-14 11:40 UTC by pawamoy

Issue #345

Draft to see how CI behaves.

2021-02-15 08:14 UTC, Yajo commented
This may be unrelated, but you might be interested in this patch I had to add in the refactor: https://github.com/copier-org/copier/blob/b3190c2abffb04d5f4b21fa71a51bf4036baad5a/copier/main.py#L285-L289

See https://bugs.python.org/issue43095 for more details.

2021-02-23 09:25 UTC, pawamoy commented
I don't think the failure on MacOS and Python 3.7 is related to my changes here. I'll add tests anyway, of course.

2021-02-23 18:45 UTC, Yajo commented
Ah... rebase please, that's fixed on master.

2021-02-24 19:46 UTC, pawamoy commented
The Poetry issue comes from its new core version. The solution is to make it less verbose: `poetry install -v` instead of `-vvv`.

2021-02-28 15:03 UTC, pawamoy commented
I'll wait for you to merge #364 and I'll rebase.

2021-03-01 14:13 UTC, pawamoy commented
Alright!

I've decomposed the process:

- [x] https://github.com/copier-org/copier/pull/358/commits/9c86e1c341f85f907431f52f1397ba7403ce25c6 adds tests for this particular issue, they pass on Windows for Python 3.8 and 3.9.
- [x] https://github.com/copier-org/copier/pull/358/commits/83915961f2f01d3306ed0855e2b89417f8048475 re-enables Windows for Python 3.6 and 3.7, tests are failing as expected
- [x] https://github.com/copier-org/copier/pull/358/commits/ce00fd7a1253908de6ad9732cf9adc5b21bafbc2 fixes the issue by implementing a more robust deletion in a temporary directory class, tests are passing again on Windows for all tested Python versions

Please **squash** as I pushed commits disabling/enabling things in CI that were only used to speed up CI.

2021-03-01 14:23 UTC, pawamoy commented
Pexpect timeout again on MacOs + Python 3.6 :confused:

2021-03-01 17:31 UTC, Yajo requested changes
Thanks!

2021-03-01 17:31 UTC, Yajo commented on copier/tools.py
> +def handle_remove_readonly(func, path, exc):
Please add docs.

2021-03-01 17:31 UTC, Yajo commented on copier/tools.py
> +class TemporaryDirectory(tempfile.TemporaryDirectory):
Also here

2021-03-01 19:19 UTC, pawamoy commented on copier/tools.py
> +def handle_remove_readonly(func, path, exc):
Done.

2021-03-01 19:19 UTC, pawamoy commented on copier/tools.py
> +class TemporaryDirectory(tempfile.TemporaryDirectory):
Done.

2021-03-03 16:08 UTC, pawamoy commented
Could you re-run the jobs to see if the codecov error goes away? Unless you already did?

2021-03-04 12:39 UTC, Yajo commented
Oh man what's up with that mac? 🤦🏼‍♂️ 

I could debug that if somebody buys me a mac. Otherwise I suggest you to mark that test as not forced xfail. 🤷🏼‍♂️

2021-03-04 16:05 UTC, merged

2021-03-04 16:09 UTC, Yajo commented
Finally! thanks 😊