Sorting match patterns
copier-org/copier pull request #736
Opened 2022-08-09 17:24 UTC by andrew-glenn

This PR closes #735

2022-08-12 06:32 UTC, yajo approved these changes

2022-08-12 06:44 UTC, yajo requested changes
Thanks for your contribution! 

However it seems to be a wrong fix, after double-checking.

If you read [upstream docs](https://git-scm.com/docs/gitignore), you will find this example:


    # exclude everything except directory foo/bar
    /*
    !/foo
    /foo/*
    !/foo/bar

It shows that processing patterns in order makes sense and is the expected behavior. OTOH, if you find the library is not matching inn the same fashion as a gitignore, then you should probably file this issue upstream, to the pathspec project. 

The correct fix would be to document it instead, or just point to upstream docs, unless I'm misunderstanding something. 

Thanks!

2022-08-12 06:44 UTC, yajo commented on copier/main.py
> +            if (("!" in i1) and ("!" in i2)) or (("*" in i1) and ("*" in i2)):
Shouldn't you use `i1.startswith("!")` and similar?

2022-08-12 15:30 UTC, andrew-glenn commented
Since `copier` is inheriting the behavior of pathspec, I think for the project, a doc change is probably the best option.

2022-08-12 15:42 UTC, closed without merging

2022-08-13 09:14 UTC, yajo commented
Don't you think that just reordering the exclusions should be enough for your use case?