fix: Make sure to delete local temporary clones
copier-org/copier pull request #802
Opened 2022-09-14 13:19 UTC by pawamoy

Closes #709

I implemented that on GitPod.io but have a lot of test failures due to pexpect timeouts, and `pkg_resources` module not being found (it seems the env on gitpod is kinda broken). Opening to see how CI behaves.

2022-09-14 13:52 UTC, pawamoy commented
OK, I was able to fix the env on gitpod by upgrading pip and setuptools in both the pyenv version and the poetry venv.

2022-09-14 15:13 UTC, pawamoy commented
Network failure in job ubuntu 3.8, re-running it should fix it.

2022-09-15 06:34 UTC, yajo commented
Don't you think we need to fix this too? https://github.com/copier-org/copier/blob/890ac866a09bcb7dcc448e6360eeaf7e0f563c13/copier/vcs.py#L133

2022-09-15 07:04 UTC, pawamoy commented
Oh, that's exactly what gets deleted by the added code. Sorry for not making it clear. I'll update the PR description accordingly.

2022-09-15 07:33 UTC, yajo commented
Maybe a cleaner solution would be to add a `destination` argument to the `clone()` function. When calling it, we already provisioned the temporary directory. This way, the ownership of that variable belongs to the worker, and it would clean it up automatically, as I feel the cleanup should be in the temporary directory class better than in the worker.

2022-09-17 13:08 UTC, pawamoy commented
I'm not sure to follow.

> When calling it, we already provisioned the temporary directory.

Where would it be? I can't seem to find an attribute or property pointing to a temporary directory in the Template class.
If you meant to create the temporary directory above `clone`, in `Template.local_abspath`, then the temporary directory is still bound to the template and not the worker.

> the cleanup should be in the temporary directory class

That would be best indeed, but I don't see how we could use it in methods/properties as it's a context manager, and the temporary clone needs to exist for a longer time than the scope of the Template class' methods/properties.

2022-09-24 12:31 UTC, yajo requested changes
I've reviewed this deeper and now I understand better what you said and why this is a good design.

I think it's good for a class to provision the paths it needs and clean them up, so let's move that logic to `Template` itself. It should be:

1. Define `Template._cleanup()`.
2. Call it in `Worker.__exit__()`.
3. Define `Template._temp_clone` as explained below.

This way, the template creates the paths and provides the way to remove it.

Adding context manager support to `Worker` also seems to be the way to go. TBH I was thinking that implementing `__del__()` would be better, but I've now learned that can lead to other problems.

Please don't forget to add a couple of tests:
1. The temporary clone is removed.
2. Copying from a local repo is not removed.

Also the API docs to use `Worker` as a context manager.

Thanks!

2022-09-24 12:31 UTC, yajo commented on copier/main.py
> +            )
I think the cleanup should exist in `Template`, which is the one that creates the directory. Then, here:

```suggestion
        self.template._cleanup()
```

2022-09-24 12:31 UTC, yajo commented on copier/template.py
> +        return self.local_abspath != Path(self.url).absolute()
I think you can just have a normal property called `_temp_clone`, which is filled up with the clone path inside `local_abspath()`, only if required.

Then add `_cleanup()` and remove that path recursively if it exists, just like you were already doing.

2022-09-27 15:26 UTC, merged