Answers file templating
copier-org/copier pull request #882
Opened 2022-12-01 04:50 UTC by EthanBar

Closes #866 

This adds support for templating in the `_answers_file` variable, allowing multiple answers files to be generated depending on answers given in `copier.yml`.

Was unsure whether to put tests in a new file or `tests/test_answersfile.py`. Went ahead and made a new file, but let me know if I should put them elsewhere.

2022-12-14 13:51 UTC, yajo requested changes
Hi there!

Thanks for the patch, it seems correct. Also thank you for the test, although it is buggy. We should test the expected and supported usage only.

I can see you got a bit mislead in where should you put the template and where not. Could you please also update the docs to help others using this feature?

2022-12-14 13:51 UTC, yajo commented on tests/test_answersfile_templating.py
> +                [[ _copier_answers|to_nice_yaml ]]
Bug with old template markers.

```suggestion
                {{ _copier_answers|to_nice_yaml }}
```

2022-12-14 13:51 UTC, yajo commented on tests/test_answersfile_templating.py
> +            / ".copier-answers-{{module_name}}.yml": """\
Follow [the docs](https://copier.readthedocs.io/en/stable/configuring/#the-copier-answersyml-file):

```suggestion
            / "{{ _copier_conf.answers_file }}.jinja": """\
```

2022-12-14 13:51 UTC, yajo commented on tests/test_answersfile_templating.py
> +                _answers_file: .answers-file-changed-in-template.yml
The real place where you want to template the name is here:

```suggestion
                _answers_file: .copier-answers-{{module_name}}.yml
```

2022-12-14 13:51 UTC, yajo commented on tests/test_answersfile_templating.py
> +    assert path.exists()
Please assert the contents too. You'll find plenty of examples across tests.

2022-12-14 13:51 UTC, yajo commented on tests/test_answersfile_templating.py
> +    assert path.exists()
Also here.

2022-12-14 13:51 UTC, yajo commented on tests/test_answersfile_templating.py
> +    assert path.exists()
And here.

2022-12-28 13:33 UTC, stefan-caraiman commented
bump, is this PR abandoned? 😢

2023-03-06 21:34 UTC, icj217 commented
I opened a new PR [here](https://github.com/copier-org/copier/pull/1027) due to the lack of activity on this PR and the fact that it didn't seem to actually work as expected during my testing. @yajo Would appreciate your 👀 on that other PR.

2023-03-29 19:13 UTC, sisp commented
@yajo This PR can be closed as it has been superseded by #1027.

2023-03-31 05:28 UTC, closed without merging